### ISSUE TITLE
Support for Resuming File Uploads to Blob Storage

### ISSUE THREAD

**Issue by gregman-msft** [Azure/azure-sdk-for-c#100]
At least 5 C SDK users have requested support for resuming paused file uploads to Blob Storage. This is especially important for large files.

Original GitHub issue: https://github.com/Azure/azure-iot-sdk-c/issues/321

**Comment by vhvb1989** [comment]
Closed as original

**Comment by thekeyman** [comment]
Why was this closed? This has not been solved. It should remain open.

"Closed as original"

The original issue Azure/azure-iot-sdk-c#321 was closed because it was moved here:

"This will require new work on the blob storage support, which we are transitioning to a new repository. I have opened up a request on your behalf in this new repository here. Please track the request there and feel free to add any additional comments."
