### ISSUE TITLE
Don't suppress linker warning about libcmtd.lib

### ISSUE THREAD

**Issue by barcharcraz** [Azure/azure-sdk-for-c#1020]
https://github.com/Azure/azure-sdk-for-c/blob/1215f7283eafd7cb16d0bd65b5da0f5cde157915/cmake-modules/AddTestCMocka.cmake#L108

This warning is important, it indicates you've mixed debug and release CRTs, or shared and static CRTs. You need to fix the mixing not just suppress the warning. If you mix libs like this many CRT calls are undefined behavior.

**Comment by ahsonkhan** [comment]
Building just the SDK components doesn't give this warning.

This warning only comes up when building tests and samples because of some of the dependencies we bring in (like cmocka , eclipse-paho-mqtt-c, etc,). I am not sure how we fix this. We don't have control over the CRT versions they are bringing in. Got any suggestions?

**Comment by kurtzeborn** [comment]
Relabeling "Client" since the work here is owned by the libraries team, not the EngSys team.  These labels (the yellow ones) are to track who owns the work.

**Comment by barcharcraz** [comment]
you need to build those dependencies with the same version of the runtime as everything else.
