### ISSUE TITLE
[BUG] .clang format should never sort includes

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#105]
CLang formatting should never change such things as compilation order. It's not formatting-tool business.

**Comment by sergey-shandar** [comment]
PR #103

**Comment by antkmsft** [comment]
I disagree - you have an option to put a newline between blocks of include files, and it won't mix them.
I find it beneficial that you won't be able to tell who wrote the code, and what was the history behind non-alphabetical order. Include order within a block should not matter, and it always should be safe to move includes within a block. It should be an assumption, or otherwise you can't trust anything.
