### ISSUE TITLE
Wrong cmake_minimum_required (should be 3.13)

### ISSUE THREAD

**Issue by kartben** [Azure/azure-sdk-for-c#1164]
Several CMakeLists.txt files make use of `add_link_options()` which only got added in CMake 3.13 so cmake_minimum_required should likely be bumped to 3.13, and maybe worth double-checking there are no other dependencies toward 3.13+

https://cmake.org/cmake/help/v3.13/release/3.13.html#commands

**Comment by ahsonkhan** [comment]
@barcharcraz - thoughts?

cc @vhvb1989

**Comment by danewalton** [comment]
It was originally 3.10 because Ubuntu 18.04 apt gets are max'd at that version. People on 18.04 would have to install from source. But if we use features in 3.13 then we should probably bump

**Comment by ahsonkhan** [comment]
@danieljurek - this is related to https://github.com/Azure/azure-sdk-for-c/issues/1170 which is assigned to you. Depending on the fix for `add_link_options`, this issue might just need to be closed without any other action.

**Comment by danieljurek** [comment]
This resulted in 2 additional issues: 

* https://github.com/Azure/azure-sdk-for-c/issues/1170 -- Removes use of `add_link_options` in cases where the cmake version is <= 3.13. This mitigates the problem of building. 
* https://github.com/Azure/azure-sdk-for-c/issues/1169 -- Get CMake 3.10 running on agents (later versions are installed by default). This is estimated at 5 complexity because there will be some refactor work to build with containers in the cases of linux and windows and installation/path modification in the case of macos.

**Comment by RickWinter** [comment]
@ahsonkhan Will this be ready for the March cycle?

**Comment by ahsonkhan** [comment]
I haven't looked at this issue for quite a while, so its unlikely this will be ready, unless we want to prioritize it. Let me know and I can take a quick look and provide an estimate.
