### ISSUE TITLE
PAL and HTTP stack both return AZ_ERROR_DEPENDENCY_NOT_PROVIDED

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-c#1290]
PAL was updated to return AZ_ERROR_DEPENDENCY_NOT_PROVIDED on az_noplatform

This is making storage sample fail when no platform is selected.
az_noplatform should be able to allow no-op for PAL functions and still allow customers to use SDK. Is that not the case anymore?

**Comment by ahsonkhan** [comment]
> az_noplatform should be able to allow no-op for PAL functions and still allow customers to use SDK. Is that not the case anymore?


No, I don't believe so. For storage APIs to behave correctly, both an HTTP stack and a PAL layer (for clock/retry policy) is needed. Failing because the user did not provide a PAL is the right, expected behavior, just like failing because no HTTP stack was provided.

The purpose of `az_noplatform` is **only** so that the SDK can `build` successfully, and if the caller doesn't rely on PAL features, it can run. The moment they use APIs that rely on the PAL, a runtime failure (to provide the right dependency) is the desired behavior.

**Comment by vhvb1989** [comment]
The team have decided to keep just one ERROR and let customer figure it out what is the missing dependency
