### ISSUE TITLE
How to add Azure sdk for c to Zephyr?

### ISSUE THREAD

**Issue by fromeijn** [Azure/azure-sdk-for-c#1357]
**Query/Question**
How to add Azure sdk for c to Zephyr with CMake?

***Why is this not a Bug or a feature Request?***
We want to see if we can use this Azure sdk in our Zephyr application, i'm unable to add it successful to my project.
i have added the following to my project CMakeList.txt

```include(FetchContent)
FetchContent_Declare(azuresdkforc
GIT_REPOSITORY      https://github.com/Azure/azure-sdk-for-c.git
GIT_TAG             1.0.0)
FetchContent_GetProperties(azuresdkforc)
if(NOT azuresdkforc_POPULATED)
FetchContent_Populate(azuresdkforc)
add_subdirectory(${azuresdkforc_SOURCE_DIR} ${azuresdkforc_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()
```

but when i try to use i get `azure/core/az_json.h: No such file or directory`

I see the AZ_SDK_VERSION during build.

Im not really familiar with CMake so a bit of help is appreciated.

I'm now just building the hello_world sample from Zephyr and try to add the library.

**Setup (please complete the following information if applicable):**

- OS: Ubuntu 20.04
- IDE: not used
- Version of the Library used: 1.0.0
- Zephyr 2.3.0

**Comment by vhvb1989** [comment]
Hello @fromeijn, happy to hear about you are exploring the Azure SDK for C

Are you using the the CMake code you shared as a module?  Can you share your CMakeList.txt?  

Also, here is a simple repo with an example about consuming the Azure SDK using that CMake module
https://github.com/vhvb1989/azure-sdk-for-c-samples
(see the helloAzure sample)

Let us know if this is helpful or if we can help you further.

**Comment by fromeijn** [comment]
Hey @vhvb1989, thanks for your reply. I tried it but still getting some errors like `undefined reference to `_ctype_'` . I have created a "hello world" repo here: https://github.com/fromeijn/hello-world-zephyr-with-azure Can you see what i'm doing wrong? Much appreciated!

**Comment by fromeijn** [comment]
maybe some useful information can be found here: https://github.com/zephyrproject-rtos/zephyr/tree/v2.3-branch/samples/application_development/external_lib

**Comment by vhvb1989** [comment]
Hello @fromeijn, 
Thanks for sharing your repo.  I took a look and learn some interesting things about zephyr.

So, in order to add 3rd party libraries as part of your zephyr app, we need to create a zephyr module (see: https://docs.zephyrproject.org/latest/guides/modules.html,  also see: https://github.com/zephyrproject-rtos/zephyr/issues/1924).

zephyr uses `west` to build. It works on top of CMake, but, when CMake calls `fetchContent`,  the generated project won't use the zephyr build env (zephyr adds a c standard lib and more board-specific libs). This basically means that any library we could built next to our application, won't be able to be linked with zephyr app if it uses functions from the standard library.

So, the right approach here is to follow up with zephyr library and find out if we can have our Azure SDK for C integrated as a zephyr module, so it would be already available for everyone directly from zephyr SDK. @ahsonkhan , I leave it up to you if you can follow up with zephyr

There is, however, a workaround, if you still want to explore the Azure SDK for C before it becomes a zephyr module (it can take a while...). Basically, instead of using CMake to built Azure SDK for C library, we need to let zephyr SDK build it as part of your application (we would merge Azure SDK for C lib and any other as one single lib).
To make this, instead of calling `target_link_libraries(helloAzure PRIVATE az_core)`, we need to add the headers folder and add all source files next to your application source files. like:
```cmake
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.13.1)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(hello_world)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake-modules")
include(AddAzureSDKforC)

# Include Azure SDK for C headers to app
target_include_directories(app PRIVATE ${azuresdkforc_SOURCE_DIR}/sdk/inc)

# Let Zephyr build all 3rd party libs with app. Merge all into one
target_sources(app PRIVATE
    # Azure SDK for C - CORE lib
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_context.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_http_pipeline.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_http_policy.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_http_policy_logging.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_http_policy_retry.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_http_request.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_http_response.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_json_reader.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_json_token.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_json_writer.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_log.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_precondition.c
    ${azuresdkforc_SOURCE_DIR}/sdk/src/azure/core/az_span.c
    # Application sources
    src/main.c)
```

Since we would be removing CMake, we need to manually control what features you want from Azure SDK for C. For instance, if we only need JSON features, we can remove the other c files (like HTTP)

I created this PR https://github.com/fromeijn/hello-world-zephyr-with-azure/pull/1 to the sample code you shared.  Using those changes would allow you to used the Azure SDK for C :)

Let me know if you have any further questions. 
And thank you for using the Azure SDK for C

**Comment by fromeijn** [comment]
Thank you, for now that will suffice. I will try it out and see. Zephyr module would be nice, but that will probably takes some time.

**Comment by vhvb1989** [comment]
Moving to Backlog for now.
Setting new estimate for adding the SDK as a zephyr module

**Comment by RickWinter** [comment]
@vhvb1989 The workaround seems fine until Zepher adds the module.  We should close this issue as there is no action or work required by us.
