### ISSUE TITLE
Program goes into an infinite loop when parsing twin topic with incorrect status

### ISSUE THREAD

**Issue by bo-ms** [Azure/azure-sdk-for-c#1421]
I am running fuzz test for Azure IoT Middleware for Azure RTOS. I got stuck in an infinite loop when testing az_iot_hub_client_twin_parse_received_topic() with incorrect topic "$iothub/twin/res//00/?$rid=2" (status: "/00").

The program goes into infinite loop at https://github.com/Azure/azure-sdk-for-c/blob/5faba13f72790d465b11ce0184c2f6e8716c89ea/sdk/src/azure/iot/az_iot_hub_client_twin.c#L143

Could we return with error value instead of going infinite loop?

**Comment by ahsonkhan** [comment]
The issue occurs while parsing the topic **before** `az_span_atou32` is called because the status span created is invalid (is empty/size 0), which triggers a precondition failure. The API expects a non-empty span. The infinite loop is coming from the precondition not being honored.
https://github.com/Azure/azure-sdk-for-c/blob/564b63be1b61324b4c8e4610a3c78f727745340f/sdk/src/azure/core/az_span.c#L158

`_az_span_token` is finding the status between the two backslashes, after `res/` and that is an empty status code.

The fix is to add a size check to the status code span before calling `az_span_atou32` OR keep tokenizing for `/` delimiter until a non-empty status code is found and error out if none was found.

![image](https://user-images.githubusercontent.com/6527137/95628026-19a7c500-0a32-11eb-986d-d48531c3791e.png)

If you pass a "valid" span string containing "/00", with size 3, to `az_span_atou32`, it will return `AZ_ERROR_UNEXPECTED_CHAR` as desired.

cc @danewalton

**Comment by ahsonkhan** [comment]
@bo-ms, if you turn preconditions off, `az_span_atou32` will correctly return `AZ_ERROR_UNEXPECTED_CHAR`:
https://github.com/Azure/azure-sdk-for-c/blob/564b63be1b61324b4c8e4610a3c78f727745340f/sdk/src/azure/core/az_span.c#L163-L166

**Comment by bo-ms** [comment]
@ahsonkhan Thank you for response, but the data from network can be any value, we should not block the device/program.

**Comment by ahsonkhan** [comment]
> but the data from network can be any value, we should not block the device/program.

When preconditions are off, we don't. Preconditions are guards for dev-time testing, and it is recommended to turn them off when you release the bits and publish to the device.

That said, I see your point, and if needed recommend fixing the issue in the `az_iot_hub_client_twin_parse_received_topic` method. Hence deferring to folks on the IoT team to decide and fix the issue how they see fit :)

**Comment by bo-ms** [comment]
Sure, let IoT team to take a look at it. Thank you.

**Comment by ahsonkhan** [comment]
@CIPop - update some docs that topic is expected to be value

**Comment by CIPop** [comment]
> Could we return with error value instead of going infinite loop?

We are still debating if the function should have an invalid return or a preconditon. We are also debating if we should have an `assert()` in addition to the infinite loop.

Regardless of that outcome, as far as I can tell from section 4.7 of the MQTT spec (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180919) this doesn't appear to be a valid MQTT topic. As @ahsonkhan said, the IoT SDK expects valid MQTT constructs and so the fix is out of scope for this code. The fact that the issue was caught by a precondition is also not something we can guarantee (memory corruption is likely if invalid MQTT or invalid buffers are passed).

@bo-ms I think the invalid MQTT part should be fixed in the MQTT client. I would like to keep this bug active though for the doc update.

**Comment by RickWinter** [comment]
@ahsonkhan Any work remaining on this issue?  Can it be closed

**Comment by ahsonkhan** [comment]
The work left for this issue is on IoT docs side.

APIs like `az_iot_hub_client_twin_parse_received_topic` should be documented to state they expect valid topics only.

> update the API docs that topic is expected to be valid, and passing invalid topic for processing will result in undefined behavior.

I will leave it up to @danewalton and others to close the issue.
