### ISSUE TITLE
How to perform Packaging using Cmake

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-sdk-for-c#1488]
Hi ,
I want to package the SDK using Cmake i have tried using Include(CPack) but there is an issue with path.
So here the issue is as i had generated Code using CMake now i want to package that but not getting how to do that.

**Comment by vhvb1989** [comment]
Hello @Abhi2109, thank you for using the Azure SDK for C!

I wonder if you could provide more context for what you want to do.
-  Are you trying to pack the SDK together with your own application?
-  Are you trying to distribute the SDK as a dependency installer for your application?

The Azure SDK for C doesn't have the required CMake instructions to use `cmake install` or `make install`. It also does not contain the configuration that is required for CPack.  We are currently only distributing the source code directly.

In order to prioritize, plan and implement the `install` and `cpack` changes for the Azure SDK, please describe your overall goal and motivation.

**Comment by Abhi2109** [comment]
Thanks Victor,
Yes what i have done , i have use this Azure SDK C source code and wrap using my own APIs (For Connecting to Hub , Send Telemetry Data etc...) now what i would like to do is to use , as you said CPack to have a package so that my client can use without knowing the internals using Libs and Header file only. 

Now what i need to know is that while using CPack , do i have to include this in all the libraries (iothub_client and other pre-existing libraries or only to the one that i have added to?).

**Comment by vhvb1989** [comment]
@Abhi2109 The configuration for installing and using cpack should be added to your main CMake files (the one where you create your app and link all the libraries).
I would expect cpack to include all the libraries to be installed and to follow the installation instructions from your main CMake.

If you need to add configuration to the Azure SDK CMake files, feel free to create a PR and the team can review it.

@RickWinter , FYI

@danewalton have you ever used cpack for any of the iot samples?

**Comment by danewalton** [comment]
nope we haven't used cpack at all

**Comment by RickWinter** [comment]
@danewalton Is this a common pattern for IoT?  The customer has not commented since November, I'm inclined to close the issue as Not supported currently.  We could look to support in the future should sufficient customer demand materialize

**Comment by Abhi2109** [comment]
One suggestion from side try put some Cpack exmaple in cmakelist so that we can refer that for our need. So as of now you can close this issue.

**Comment by danewalton** [comment]
Hey @Abhi2109 this definitely seems like an interesting use case. We would be happy to review any specific suggestions you have but it would be easier if you have concrete examples/usage scenarios that you're looking to build out. Any links to projects you think are doing it correctly, repos you have yourself which is attempting to ingest it this way, etc.
