### ISSUE TITLE
aziot_esp32 fails with Arduino Espressif ESP32 2.0.0-rc2

### ISSUE THREAD

**Issue by RLmonitor** [Azure/azure-sdk-for-c#1882]
Upgrading the Arduino ESP32 board resources to the latest breaks the MQTT communication with the Azure hub.

![image](https://user-images.githubusercontent.com/6611090/131278042-e3006c6f-32e6-4dd8-82a7-413f9dd6a752.png)

Sample code compiles & runs with ESP32 board 1.0.6.
Update via Arduino boards manager to 2.0.0-rc2.
The code compiles ok, but crashes after "MQTT client started"

```
static int establishConnection()
{
  connectToWiFi();
  initializeTime();
  initializeIoTHubClient();
  (void)initializeMqttClient();
}
```

**Setup (please complete the following information):**

- OS: Win10
- IDE: Arduino 1.8.13
- Azure/azure-sdk-for-c 1.1.0

**Comment by wduraes** [comment]
Hey @RLmonitor, pre-release versions like this one are normally less stable and more prone to random errors than the latest stable version which is the 1.0.6. They're also not recommended for production scenarios, which is why we test - and you confirmed - version 1.0.6 works fine with the ESP32 and Azure IoT. This is the reason why we don't support release-candidate versions, until they become a stable release.

**Comment by RLmonitor** [comment]
Thanks for your comments. I'll look forward to the release version. I was testing RC2 as it has a fix for a hang when the UART is initialised and there is incoming data.
