### ISSUE TITLE
CI needs check hyperlinks for being valid, for not having `en-us`, etc.

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-c#1980]
C++ repo has this, I think we should enable it as well.

On the other hand, most of the `en-us` and `/master/` links that I've seen are in the source code comments, so if that's not something that the tool does, and if it is already enabled, then I'm sorry for the false positive.

**Comment by antkmsft** [comment]
@weshaggard: "You are correct that we don't validate random links in any text we only look at well formed links in MD or html. This has come up in .NET XML doc comments recently, [Azure/azure-sdk-for-net#22216](https://github.com/Azure/azure-sdk-for-net/issues/22216), although we don't have a solution for that currently either. It can be tricky to parse out links in random source code."

**Comment by kurtzeborn** [comment]
It seems like what you're talking about here is links in comments in our source code.  We could try to do this, but the solution wouldn't hacky and specialized and probably produce a lot of false positives.  I'm going to go ahead and close this since I don't think the priority of doing this is higher than most things on our backlog.  I'm certainly open to alternate opinions though, so if you disagree with this conclusion, please reactivate.
