### ISSUE TITLE
Azure IoT Hub Client blindly copies user agent option

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#1984]
Thanks to @ewertons for finding.

Here we copy the user agent string and append it as a property. If the user sets it to a custom value, it gets appended without the "key" part of the "key value pair". 

https://github.com/Azure/azure-sdk-for-c/blob/c66093ab0da854ce071c2567a8b714e0f6a5a079/sdk/src/azure/iot/az_iot_hub_client.c#L104-L108

Aka
```c
options.user_agent = "xyz";

// This then gets appended as 
{iothubhostname}/{device_id}/?api-version=2018-06-30&xyz

// instead of 

{iothubhostname}/{device_id}/?api-version=2018-06-30&DeviceClientType=xyz
```

**Comment by ewertons** [comment]
There is more to that, I would like to ask if we could have the following:

1. User agent string (in azure-sdk-for-c) to always include SDK and version, and append the user defined prefix (e.g., "xyz") if provided. Reasons: a) We then will have a minimum UA string always present, b) upper layers (middleware) do not need to re-encode the "c/<version>" as a prefix if they set the UA string (which they do);
  Examples:
  c/1.0.0
  c/1.0.0(xyz)
2. Have a short form for the "DeviceClientType" property name. Suggestions: "ua", or "dct".

**Comment by JeffreyRichter** [comment]
Azure SDK's telemetry guidelines are here: https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy
For HTTP, this means the user-agent looks like this:
   [<application_id> ]azsdk-<sdk_language>-<package_name>/<package_version> <platform_info>

I'm pretty sure we do not have support for this in our C SDK now because customers would opt out of it due to the extra bandwidth issues.

So, right now, Azure core has no support for "telemetry".
Your client library can add a constant string with <package_name>/<package_version> and prepend the customer <application_id> to this when appending the the "query param" to the MQTT topic string.

I don't think we should have this in Core because you want your package name & version in the string; not core's version.
