### ISSUE TITLE
Clean up EngSys branches

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-c#2018]
https://github.com/Azure/azure-sdk-for-c/branches/all

Some branches look like they are personal branches, some are stale. Almost all belong to EngSys, so I suggest to assign this work item to them.

I think there should not be personal or engsys branches at this point, that are only made for the purposes of making a PR. Instead, you fork the repo, create the branch there, and create a PR to this repo - just as we do with our dev branches.

If it is a feature, or another branch of this sort, intended for long life, it is ok.

**Comment by kurtzeborn** [comment]
The "sync-eng" branches will get cleaned up automatically (and at the time of this comment there were only 3 of those).  However, @danieljurek, you have 7 branches open on this repo.  Any of those that can be cleaned up should be.  Also, consider forking the repo and branching there rather than creating a branch in the repo (I know this won't work with some pipeline work we do, so not a 100% solution).
