### ISSUE TITLE
JSON parser escaping/un-escaping

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-c#2173]
One of the main Azure IoT Provisioning Client purposes is to provide easy access to data within payloads received from the service. Today, it does this using `az_span`s pointing within the original buffer. 

This issue is discussing solutions to zero-memory allocation escaping/un-escaping.

## Proposed solutions:
1. In-place un-escaping of strings. This will alter the original buffer and destroy the JSON document.
2. Returning raw (escaped) strings and allowing the application to un-escape them. Today, the `az_json_token_get_string` will not work without a JSON context. Since we return the string only (within an `az_span`), the function cannot be used.

----

## Example snippet from the client's implementation returning the raw JSON element:

```C
    if (az_json_token_is_text_equal(&jr->token, AZ_SPAN_FROM_STR("assignedHub")))
    {
      _az_RETURN_IF_FAILED(az_json_reader_next_token(jr));
      if (jr->token.kind != AZ_JSON_TOKEN_STRING)
      {
        return AZ_ERROR_ITEM_NOT_FOUND;
      }
      out_state->assigned_hub_hostname = jr->token.slice;
      found_assigned_hub = true;
    }
```
We expect that `assigned_hub_hostname` does not contain any escaped characters and that the `az_span` contained string can immediately be used to connect to the assigned IoT Hub.

----

## Example for solution 1: in-place escaping:

```C
if (az_json_token_is_text_equal(&jr->token, AZ_SPAN_FROM_STR("issuedClientCertificate")))
    {
      _az_RETURN_IF_FAILED(az_json_reader_next_token(jr));
      if (jr->token.kind != AZ_JSON_TOKEN_STRING)
      {
        return AZ_ERROR_ITEM_NOT_FOUND;
      }

      // Un-escape JSON string in-place.
      int32_t new_size = 0;
      _az_RETURN_IF_FAILED(az_json_token_get_string(
          &jr->token,
          (char*)az_span_ptr(jr->token.slice),
          az_span_size(jr->token.slice),
          &new_size));
      out_state->issued_client_certificate = az_span_slice(jr->token.slice, 0, new_size);
    }
```

---

## JSON Parser API request for solution 2 above:

```C
/**
 * @brief Gets the JSON token's string after unescaping it, if required.
 */
AZ_NODISCARD az_result az_json_string_unescape(
    az_span json_string,
    char* destination,
    int32_t destination_max_size,
    int32_t* out_string_length);
```

**Comment by CIPop** [comment]
After today's discussion, we've landed on a combined solution:

* A new API similar to the above option 2, `az_json_string_unescape` will be added to give the application full control over JSON string unescaping.
* The new API *may* be able to unescape using the same buffer (TBD).
* The SDK will continue to expose `az_span` objects in the original buffer without public API modification.

**Comment by gearama** [comment]
E.G. https://www.freeformatter.com/json-escape.html 
or replace %XX <-> charater <- this looks more like URL encoding than escaping anythign

**Comment by gearama** [comment]
> Example where the "in-place" would go:
> 
> https://github.com/Azure-Samples/iot-middleware-freertos-samples/blob/b235b0d40aab83e749d072b2ec7ca416f515f657/libs/azure-iot-middleware-freertos/libraries/azure-sdk-for-c/sdk/src/azure/iot/az_iot_adu_client.c#L444-L448

Do we have such an example for the main branch ? this file is not in main, so i'm not sure what this example shows since it will not be valid for anyone but you

**Comment by gearama** [comment]
Got answer from @ahsonkhan 
[3:30 PM] Ahson Khan
Typical JSON looks like this:
{"Name" : "George"}
What happens if the property or value strings have some special characters, like embedded quotes. They need to be escaped to avoid confusion.

Example:
{"Name" : "George the \"Glorious\""}
[3:32 PM] George Arama
right , that glorious one thanks you for the  example. 

[3:33 PM] Ahson Khan
Any character in a JSON string can be escaped: https://datatracker.ietf.org/doc/html/rfc8259#section-7
Either with \ or in it's full Unicode from \uXXXX (4 digit utf-16 code unit).
 like 1
RFC 8259 - The JavaScript Object Notation (JSON) Data Interchange Format
The JavaScript Object Notation (JSON) Data Interchange Format (RFC 8259)

[3:36 PM] George Arama
thank you sir , much appreciated

**Comment by CIPop** [comment]
> Do we have such an example for the main branch ? this file is not in main so for my edification it would be of more help

Not in the main branch but in preview: https://github.com/Azure/azure-sdk-for-c/blob/feature/iot-certificate-management/sdk/src/azure/iot/az_iot_provisioning_client.c#L368

**Comment by ahsonkhan** [comment]
@CIPop I would be cautious when doing such destructive parsing, since subsequent attempts to read the JSON in the payload will fail (since unescaping turns the valid JSON into potentially invalid). In the space of sending network requests, with retries, let's be careful that such patterns only happen once we know something else won't go wrong in the middle, having to retry the parsing again.

Also, as far as the JSON reader is concerned, theoretically it has moved past that token, while parsing it, but such scenarios, where the data is being changed underneath it isn't really supported.

Lastly, just note, this API accepts an az_span. So, if you need to unescape data which is in blocks of non-contiguous memory, I recommend sticking to the existing az_json_token get_string method.

**Comment by CIPop** [comment]
To close the discussion here: we have selected option 2 where the application developer will take the decision depending on RAM availability and buffer lifetime. I apologize for the example without explanation: the code above will be replaced with simply returning the `az_span`. The application _may_ decide to use the information which requires unescaping.

Re destructive parsing: For example, for Mosquitto MQTT async, the payload buffer is available on the receive callback stack only. Once the application returns, the data is lost. Since parsing and changing the FSM state should be fast CPU-bound operations, the processing can usually be made within the callback, prior to buffer release. In some cases, the information isn't needed at all and can be ignored. Unfortunately, due to how JSON can change ordering of elements, we need to parse the entire document regardless (but we don't need to unescape unless the application needs the information).
