### ISSUE TITLE
Best option for QuecOpen?

### ISSUE THREAD

**Issue by rschiefer** [Azure/azure-sdk-for-c#2284]
Considering using QuecOpen, is embedded iot sdk best option for this?  anyone tried it?

https://www.quectel.com/how-to-enable-lte-and-your-application-on-a-single-chip-with-quecopen

**Comment by liydu** [comment]
Hi @rschiefer, our current implementation around using cellular like Quectel is the host MCU + modem mode:
![image](https://user-images.githubusercontent.com/17307692/181374584-734cd835-c19e-4869-b914-c9bfc4389573.png)

You have all your device application including the Embedded C SDK running on the host MCU, modem is connected via serial interface like UART. Device application calls AT command set to perform the cellular connections.

The OpenCPU mode (as QuecOpen) we did not use because 1) the implementation is unique to each module vendor. 2) developers are more familiar to deal with normal MCUs than modules, and MCU vendors like ST also provides this [middleware](https://www.st.com/en/embedded-software/x-cube-cellular.html) to make it easier to work on.

Happy to understand more about your use case.
