### ISSUE TITLE
Need examples for Realtek RTL8720DN to communicate with Azure IoT Central 

### ISSUE THREAD

**Issue by electro89** [Azure/azure-sdk-for-c#2362]
Where can I get the support for Realtek RTL8720DN chip  with Azure IoT Central?

**Comment by wduraes** [comment]
Hi @electro89, since we don't currently have a sample showing how to use the RTL8720DN with IoT central, one way to solve for it would be for you to adapt the sample for the [ESP32 with IoT Central](https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Central_ESP32). Since this seems to be useful to others, I'll add this ask to the backlog, but since we already have several other priorities, I can't promise when we'll have this ready.

**Comment by electro89** [comment]
Thank you, I hope ESP32 will release wifi dual band which can support 5G chip soon.
