### ISSUE TITLE
Clang formatting checks stopped working in pipelines

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-c#2560]
The clang formater stopped working in pipelines

https://dev.azure.com/azure-sdk/public/_build/results?buildId=2746005&view=logs&j=fdb9ce2e-b1c4-56cd-06a6-8aba558b4164&t=c8e1e8ad-dbab-5363-6903-52824efada30

**Comment by ahsonkhan** [comment]
A solution is to use the available version of clang-format on the box, like we do in C++, rather than hard coding `clang-format-9`.

This is the area that needs to be updated:
https://github.com/Azure/azure-sdk-for-c/blob/ac81f122da3b57d55a8a2834e993c8a557671a27/eng/pipelines/templates/jobs/archetype-sdk-client.yml#L362-L365

There is a version available on `Agent: azsdk-pool-mms-ubuntu-2004-general 22`:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=2745590&view=logs&j=5312c7ff-5558-5a0c-4f25-5356448c148b&t=5ee665bd-8bc0-590e-7be1-fd4d1361eaaf

https://github.com/Azure/azure-sdk-for-cpp/blob/8ee7d452ab4e8e8f4bec54238bfdd3aa40b541d1/eng/pipelines/templates/jobs/ci.tests.yml#L115-L122

This is what we used to do prior to https://github.com/Azure/azure-sdk-for-c/commit/e8f105e711838630cedc32f047811e69350d2de0, and I am not sure why we decided to go with version 9, but I think the reason was to pick one that is compatible with latest Ubuntu. If clang-format 11 is available on the box and works, and the formatting isn't too different, we can use that (and adjust the .clang-format file to minimize any changes we don't want in style).
