### ISSUE TITLE
Where to comment the X509 #define

### ISSUE THREAD

**Issue by georgethomas08** [Azure/azure-sdk-for-c#2566]
Hi Team,

I'm trying to send the telemetry from ESP32, I got the sample program , after reading the README I'm confused, I would like to know in which all files I need comment the X509 parameters ? I don't want to use X509 certificates Kindly help please

**Comment by vaavva** [comment]
Hello @georgethomas08! Are you using the [arduino sample for ESP32](https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Hub_ESP32/readme.md)?
To use Symmetric Keys instead of X.509, you don't need to make any changes, just leave [this line](https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Hub_ESP32/iot_configs.h#L13) commented out
