### ISSUE TITLE
PAL implementations

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#321]
We need a solution for building PAL abstractions on various platforms.
The solution ideally isolates each PAL implementation such that consumers need only have the dependencies for their target PAL present.

**Comment by barcharcraz** [comment]
This may have some packaging ramifications. Unless we go for the runtime binary module route (requires dynamic allocations) the choice of PAL will be baked in when the sdk is built, this could be a feature in the vcpkg package, however that would make the vcpkg version not very usable for users supplying their own PAL implementation (this may be fine).

**Comment by barcharcraz** [comment]
OK I took a crack at it and came up with:

https://devdiv.visualstudio.com/Personal/_git/chbarto?path=%2FPAL_example

basically the user makes a cmake target and sets our cache value to that, we can include a preset list of PALs we ship w/ the SDK.

Notice that the PAL's are added with `add_subdirectory(... EXCLUDE_FROM_ALL)` this means they only get built if they are used, and it means that the invalid (on windows) code in, for example, the C11 version isn't a problem on windows.

The API is very intentionally identical to what's in C11 (erm gmtime_r may be C2x...) so that if someone already has a crt for their platform they won't need to do anything to support us. After all the C standard library is a bit of a PAL in it's own right)

**Comment by barcharcraz** [comment]
also, the windows version is intentionally implemented in terms of the win32 API and not the ucrt, that's for illustration only and we may as well use the ucrt on windows.

**Comment by antkmsft** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/374
