### ISSUE TITLE
[QUERY] az_span length and capacity as int32_t

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#340]
Is there a technical reason why these values are `int32_t` instead of `uint32_t`.
[Link](https://github.com/Azure/azure-sdk-for-c/blob/1ed90fbe699c15cd308cd4c8dcd45c3e40205a31/sdk/core/core/inc/az_span.h#L22-L23)

**Comment by gilbertw** [comment]
The only technical reason I can think of is looping and overflow.  Though I'm not sure that was the actual reason they are signed values.
C++ std:span uses a size_t for length / capacity.  I'm inclined to keep our span similar and switch to unsigned values as well.  @JeffreyRichter thoughts on this design decision?

**Comment by danewalton** [comment]
Yea in my head signed values don't make sense for length or capacity

**Comment by JeffreyRichter** [comment]
We specifically chose signed to help us find bugs. First, we think that a range of 2 billions is good enough, and that we don't need a range of 4 billion - if you think this assumption is wrong, let's hear about it.  Assuming the 2 billion range is good enough, then signed lets us do loops better and catch errors in any math calculations: if the number ever goes negative, we know we have a bug and we can hook up a debugger and have it watch for when the integer goes negative to find the line of code that has the bad math and fix it easily & quickly. 

I understand (and agree) that length and capacity can never be signed but this is why we chose signed; to find bugs quickly (and loops).

**Comment by andre2007** [comment]
I also wondered about the data type and understand now, it is a safety measure to overcome a deficiency of C.

You may have a look at BetterC. While it almost looks like C and you only have to change little coding it comes with major benefits. You still have exact the same build results with exact the same C function signatures.

https://dlang.org/blog/2017/08/23/d-as-a-better-c/

And as example, changing a C application to BetterC:
https://dlang.org/blog/2018/06/11/dasbetterc-converting-make-c-to-d/

tl'dr:

> What may be initially most important to C programmers is memory safety in the form of array  overflow checking, no more stray pointers into expired stack frames, and guaranteed initialization of locals. This is followed by what is expected in a modern language — modules, function overloading, constructors, member functions, Unicode, nested functions, dynamic closures, Compile Time Function Execution, automated documentation generation, highly advanced metaprogramming, and Design by Introspection.

**Comment by danewalton** [comment]
Few thoughts:
1. Every cast that you have to do incurs a possible point for a bug. It would be a good idea to reduce these to the extent we can.
2. [Example here](https://github.com/Azure/azure-sdk-for-c/blob/1ed90fbe699c15cd308cd4c8dcd45c3e40205a31/sdk/core/core/inc/az_span.h#L125) which uses `sizeof` to set a signed int when it returns a `size_t`. Using signed integers in places where the values with which they are expected to be initialized are unsigned values opens us up for bugs.
3. More holistically, I'm not sure about designing values/structures/code to cover for the case where it may be wrong instead of for the case where it is correct. We are essentially baking in irremovable debugging code at the cost of typical usage.
4. **C99 Spec 6.2.5:** "...A computation involving unsigned operands can never overflow,
because a result that cannot be represented by the resulting unsigned integer type is
reduced modulo the number that is one greater than the largest value that can be
represented by the resulting type." In this case we don't have an issue with overflows.

**Comment by antkmsft** [comment]
BTW, assuming that we use signed ints for size and capacity, can we internally use the negative length/capacity range as an indication of read-only-ness? It could be useful for the values that are located in the text segment, so that we won't allow the code to to modify a single letter in the AZ_SPAN_FROM_STR("Hello world").

**Comment by JeffreyRichter** [comment]
@danewalton: I'm not sure what you're trying to say. I agree with you that casts should be avoided and we try to do so. The example you link to using sizeof does not use any casts so I think you're OK with this? If not, propose some change to the code? I do not think there is a potential bug here because the sizeof and division is calculated at compile time and assigning it to a signed int32 without a cast should cause a compiler error if the result doesn't fit. So, my confidence in this code is high.

I don't understand what you're saying with your point #3. I'm always trying to design code so that bugs are easy to find. Bugs always happen and anything to make them easier to track down is extremely helpful. Spans don't need the extra 2GB of range and so making them signed enables some useful patterns. I think you're trying to say that it feel "natural" for the length and capacity to be unsigned and therefor they should be. I agree that unsigned feels natural but many bugs happen when using unsigned integers. See https://www.learncpp.com/cpp-tutorial/unsigned-integers-and-why-to-avoid-them/ for some examples. And, watch this: https://www.youtube.com/watch?v=Puio5dly9N8&t=2560

About your #4: When I used the term "overflow," I meant that the value can wrap around and wrapping to a negative value is a clear indication of a bug since length/capacity should never be negative. Spec 6.2.5 says that "overflow" doesn't cause an error on wrap but that it just wraps. I'm happy to retract my use of the word "overflow" and replace it with "wrapping" instead. The problem still remains - we'd like to easily detect any unexpected wrapping that happens when manipulating length/capacity.

@antkmsft: No, we cannot use negative values for this as it is way too dangerous. Our code AND customer code would have to have code everywhere that checked the length/capacity for a negative value and possible negate it (if it is negative) to perform calculations with the length/capacity. This would make working with spans far more difficult and error prone. 

For example, if someone forgets to check if the length is negative, writing to ptr[length] corrupts memory before the buffer; this bug (forgetting to check for negative values and negating them) would be near impossible to find and fix. And, this affects customer code; not just our SDK code - way too scary.

**Comment by JeffreyRichter** [comment]
Here's Google C++ style guide: https://google.github.io/styleguide/cppguide.html
Search for "unsigned" to see that they also encourage signed ints over unsigned ints.
@barcharcraz: We should add similar guidelines to our Azure guidelines.

**Comment by CIPop** [comment]
I'd like to bring another issue to to using int32_t for capacity: we plan to support 8 and 16bit MCUs as well. Forcing all string operations to use 32bit is wasteful in both CPU/battery as well as flash size (as the 32bit operations need to be implemented in code).
One way to solve this is by having typedefs for each int's usage (most RTOSes and OSs support this today) or using size_t which is itself a platform-specific typedef for expressing sizes. We could also have az_span_8 and az_span_16 depending on how big the buffers need to be.

**Comment by danewalton** [comment]
@JeffreyRichter Just as a note at the end of the learncpp link you sent this is the closing line:
> Also note that if you’re developing for an embedded system (e.g. an Arduino) or some other processor/memory limited context, use of unsigned numbers is more common and accepted (and in some cases, unavoidable) for performance reasons.

Considering that is our intended audience that should likely be heeded.

**Comment by barcharcraz** [comment]
@JeffreyRichter  agree, added to my todo list (which is getting pretty long).

As for using smaller values on smaller MCUs: I see your point, but I'd be a little uncomfortable having typedefs for the width of buffer sizes, esp if embedded people are setting them to rather narrow values (16 or 8 bit). It just seems like it's asking for over/underflow bugs. That said Casey Carter pointed out that if the size is less than sizeof(int) it's going to be implicitly promoted to int anyways, and the benefits of signed sizes apply.

I think making it a compile time option is a necessary evil for supporting small mcus, and I don't see the harm in reducing the size on platforms where you can't even address 32k anyway.

**Comment by CIPop** [comment]
> As for using smaller values on smaller MCUs: I see your point, but I'd be a little uncomfortable having typedefs for the width of buffer sizes, esp if embedded people are setting them to rather narrow values (16 or 8 bit). It just seems like it's asking for over/underflow bugs. That said Casey Carter pointed out that if the size is less than sizeof(int) it's going to be implicitly promoted to int anyways, and the benefits of signed sizes apply.

> I think making it a compile time option is a necessary evil for supporting small mcus, and I don't see the harm in reducing the size on platforms where you can't even address 32k anyway.

Sounds good. Making it an `int` or `size_t` would automatically take care of the problem I think. Allowing for conditional compilation is acceptable as well. Why not define a `typedef` for string types in this case? (it can default to uint32_t)

**Comment by barcharcraz** [comment]
I think a better default might be better to use size_t if sizeof(size_t) < sizeof(int) and “ssize_t” (not standard, but size_t except signed) otherwise. Then again we use unsigned sizes in c++ stdlib and the world has not collapsed (yet).

**Comment by JeffreyRichter** [comment]
For the public preview, we are going to keep int32_t. We can revisit this if customer feedback warrants it.

**Comment by SamuelMarks** [comment]
Was about to write an issue about this, then found this.

Would like to reopen discussion. `size_t` or even `ssize_t` (if you want to keep negative one as error) are the expected types for sizing in C, and for reasons referenced earlier in this thread, would be more correct and less wasteful in C/C++.

**Comment by JeffreyRichter** [comment]
I'm ecstatic that you/others may find the generic parts useful. However, our charter is Azure SDKs and so we can only support customers using our code to communicate with Azure services.
