### ISSUE TITLE
[QUERY] How to build the sample blobs_client_example.c

### ISSUE THREAD

**Issue by andre2007** [Azure/azure-sdk-for-c#363]
**Query/Question**
It is unclear how to build the sample `blobs_client_example.c`. Just executing `cmake . && make` results in error:

>Scanning dependencies of target blobs_client_example
[ 50%] Building C object CMakeFiles/blobs_client_example.dir/src/blobs_client_example.c.o
/azure-sdk-for-c/sdk/storage/blobs/samples/src/blobs_client_example.c:4:10: fatal error: az_credentials.h: No such file or directory
 #include <az_credentials.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/blobs_client_example.dir/build.make:62: recipe for target 'CMakeFiles/blobs_client_example.dir/src/blobs_client_example.c.o' failed
make[2]: *** [CMakeFiles/blobs_client_example.dir/src/blobs_client_example.c.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/blobs_client_example.dir/all' failed
make[1]: *** [CMakeFiles/blobs_client_example.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu
 - IDE : VSC
 - Version: master
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [ ] Setup information Added

**Comment by vhvb1989** [comment]
@andre2007 , blobs_client_example currently depends on az_core and libcurl to be installed/compiled because it needs to be linked to it.
see: https://github.com/Azure/azure-sdk-for-c/blob/master/CMakeLists.txt#L37

So, if you want to build samples, we first need to make sure libcurl is installed in the system (or set up vcpkg and installed from it)

then, from root folder, generate cmake files with
```bash
cmake -DBUILD_CURL_TRANSPORT ..
make
```
this will build samples and use http transport implementation that we have using libcurl.

If you want to implement your own transport implementation (with http or other protocol) let me know and I can provide more info about how to do this.  But, just as a heads up, we are currently working to update the way this is currently working to have it as a PAL.

**Comment by andre2007** [comment]
Thanks a lot, works fine.
