### ISSUE TITLE
[BUG] Negative tests disabled due to precondition in unit tests

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-sdk-for-c#467]
**Describe the bug**
[Filing this issue with details from @danewalton ]

According to investigation is looks like this code blocks negative unit tests:
https://github.com/Azure/azure-sdk-for-c/blob/34c8b78dd70d07c93e8fb63b3e865351da223a5e/sdk/core/core/src/az_precondition.c#L11-L18

As a result ALL negative tests in this unit had to be disabled, which is a huge miss of coverage:
https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/iot/core/tests/cmocka/az_iot_sas_token_tests.c#L258

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Negative unit tests should be always enabled and running on the gates.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Any
 - IDE : Any
 - Version of the Library used: post https://github.com/Azure/azure-sdk-for-c/commit/34c8b78dd70d07c93e8fb63b3e865351da223a5e#diff-56e433353cf01b3fba4835d16d40282d

**Additional context**
By no means we should disable unit tests on the gates for existing libraries.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [x] Setup information Added

**Comment by vhvb1989** [comment]
I believe there is not a miss of coverage, because those cases will actually never happen anymore.
Precondition introduces functions as never-failing functions. 

See current iot coverage
![image](https://user-images.githubusercontent.com/24213737/76784862-a676f280-6771-11ea-85fb-6d8753ed1bff.png)

Precondition won't reduce coverage. See the only missing branches here:
![image](https://user-images.githubusercontent.com/24213737/76784939-cd352900-6771-11ea-8914-e816d0684f7a.png)

![image](https://user-images.githubusercontent.com/24213737/76784999-dfaf6280-6771-11ea-96e5-5156153d13b4.png)

**Comment by danewalton** [comment]
> because those cases will actually never happen anymore.

Not exactly true. Lets take an example where I intended for an precondition to be set but I forgot. Maybe not checking for a parameter not being `NULL`. That will go unchecked and could slip in when a unit test which ensures it would go to a precondition hook otherwise would have been guaranteed. We need to have a way to test that things which we want to be a precondition are indeed preconditions. Otherwise we just have to eyeball it. (A more complex example may be a value has to be within a certain range).

**Comment by ewertons** [comment]
Ok, this has been addressed now. Thanks.
