### ISSUE TITLE
[FEATURE REQ] CI/CMake should generate documentation using Doxygen

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#47]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by sergey-shandar** [comment]
https://github.com/Azure/azure-sdk/pull/748/files

**Comment by danieljurek** [comment]
We presently generate doxygen documentation on a per-library basis. This fits how documentation is generated and published for other languages. At this time we aren't able to produce per-library documentation from cmake. 

Closing this because we're generating documentation today. It would be nice to be able to use cmake to generate per-library documentation in the future (and not require the lengthy Doxyfile template)
