### ISSUE TITLE
CMake and CI

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#5]
See the PR #3 

CMake convention is to use `build` folder as output folder (for build artifacts).

`azure-sdk-for-c` will contain multiple project. We do have two options:

1. every project should have its own `build/` folder.
   ```
   cd sdk/storage/storage/
   mkdir build
   cd build
   cmake ..
   cmake --build ..
   ```
   Or
   ```
   cmake -S sdk/storage/storage -B sdk/storage/storage/build
   cmake --build sdk/storage/storage/build
   ```
   Or
   ```
   cd sdk/storage/storage/
   cmake -S . -B build/
   cmake --build build/
   ```
1. we use one global `build/` folder. How do build multiple projects into the same `build/` folder?

**Comment by sergey-shandar** [comment]
@bsiegel which option do you prefer?
@barcharcraz what's the best practice for CMake and multiproject repo?

**Comment by bsiegel** [comment]
I feel like having each project have its own build folder is the best approach. We do this with other monorepos already. The build pipeline will be able to publish build artifacts from all of the different build folders.

**Comment by barcharcraz** [comment]
For cmake monorepos it's common to do both. The example cmake file in #2 is designed so that you can call `add_subdirectory` from a parent folder and it will behave nicely.

Also: the build folders can be anywhere you want, and for the CI machines I would make them totally outside of the checked out repo (especially since they CI may build multiple different configurations)

**Comment by barcharcraz** [comment]
The most important things are to have your dependencies that will live in the same monorepo export targets (with install(EXPORT)) and make sure that you always create an alias target so that you can use the project the same way if you found it "on the system" with find_package as you can from the build tree.

I think we'll want a central core repo pretty fast, and that can demonstrate this.
