### ISSUE TITLE
[FEATURE REQ] CI should build for 32 and 64 bit platforms

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#51]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by barcharcraz** [comment]
the way to do this is with a toolchain file. for 32bit/64bit on windows just have the correct compiler in path or, if using the VS generators pass the `-A` option to cmake as described here: https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html

for clang/gcc on unix you need to do some additional stuff in a toolchain in order to make sure the compiler can find the correct libraries for the target system. This is particularly important for cross compiling x86/x64----->arm/arm64/mips/whatever
