### ISSUE TITLE
az_http_response_get_next_header must reject invalid header field-names including whitespace between it and the colon

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#604]
header field-names must only consist of characters that are valid according to https://tools.ietf.org/html/rfc7230#section-3.2.6
All others are considered invalid and should be rejected. This includes having whitespace in between the field-name and the field-value.

```C
    // Invalid header field name (with space before colon)
    az_span response_span = AZ_SPAN_FROM_STR( //
        "HTTP/2.0 205 \r\n"
        "header1()<>= : some value\r\n"
        "Header2:something\t   \r\n"
        "\r\n");

    az_http_response response = { 0 };
    az_result result = az_http_response_init(&response, response_span);
    assert_true(result == AZ_OK);

    // read a status line
    {
      az_http_response_status_line status_line = { 0 };
      result = az_http_response_get_status_line(&response, &status_line);
      assert_true(result == AZ_OK);
    }
    
   // read a header1
    {
      az_pair header = { 0 };
      result = az_http_response_get_next_header(&response, &header);
      assert_true(result == AZ_OK);  // This should have failed
      // This is wrong, header names should not contain those characters
      assert_true(az_span_is_content_equal(header.key, AZ_SPAN_FROM_STR("header1()<>= ")));
    }
```

The current implementation just scans and skips until we find the first colon, treating all the characters until it as part of the header field-name. This needs validation.

https://github.com/Azure/azure-sdk-for-c/blob/3ab349ffca71a52942d7b9b7921a9cf65100dae3/sdk/core/core/src/az_http_response.c#L166-L179

From https://tools.ietf.org/html/rfc7230#section-3.2.4:
> No whitespace is allowed between the header field-name and colon.  In
   the past, differences in the handling of such whitespace have led to
   security vulnerabilities in request routing and response handling.  A
   server MUST reject any received request message that contains
   whitespace between a header field-name and colon with a response code
   of 400 (Bad Request).  A proxy MUST remove any such whitespace from a
   response message before forwarding the message downstream.

cc @vhvb1989

**Comment by ahsonkhan** [comment]
@gilbertw - I have marked this for the May milestone, please update it if you disagree.

**Comment by gilbertw** [comment]
I agree we need to fix

**Comment by vhvb1989** [comment]
I think we should not make any validation in any direction, either Client to Server or Server to Client.

Also, we rely on the http stack, so I wonder if curl will fail...

And regardless the http stack, if we choose to fail an http request because the response returned with an invalid header, customer still need to see that response. Even if response is not a 200, for whatever response we got from a service, we are responsable to deliver that to customer without alterations or validations on it. Then only thing we validate is range, so we fail if response is bigger than provided buffer.

**Comment by vhvb1989** [comment]
This is still marked as to be implemented before May Release.
@gilbertw  @JeffreyRichter  Can you take a look and decide if we need it or not please?

**Comment by JeffreyRichter** [comment]
First, lets be clear about section 3.2.4 of the RFC states: "A server MUST reject ...". We are building clients; not servers. That being said, we can easily look up each header name/value character to ensure that it is within a valid ranges and if not, error out. So, we should do this. And, we should skip whitespace before/after a header value.

**Comment by gilbertw** [comment]
For now the optional whitespace on headers should be removed.  No other validation will be performed.  Post May release we will review the validation strategy.

**Comment by vhvb1989** [comment]
about invalid header name, if it is from request to server, any http 1.0 server implementation will return
```html
HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=us-ascii
Server: Microsoft-HTTPAPI/2.0
Date: Tue, 28 Apr 2020 17:17:19 GMT
Connection: close
Content-Length: 339

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Header</h2>
<hr><p>HTTP Error 400. The request has an invalid header name.</p>
</BODY></HTML>
```

If it is a header from Server to Client, that would means Server issue.  We would be adding a validation for something that is likely to never happen and for each header we parse

**Comment by vhvb1989** [comment]
About the extra spaces, libcurl uses space as the last character of header name, and removes any spaces from the beginning and from the end of header value.
So, see next examples:
```c
// adding a header like `"header  ":"  text  spaced   "`
AZ_RETURN_IF_FAILED(az_http_request_append_header(
      &hrb, AZ_SPAN_FROM_STR("header    "), AZ_SPAN_FROM_STR("    text   spaced   ")));

// This header is sent by curl as `"header":"text spaced"`
```
So we don't really need to make str trimming or anything like that when sending a request.

Then, upon receiving a header, we would be again validating if there are spaces for each header, something that would be ultra weird to happen. We would be adding something thinking that a Server wants to give unsafe http response to customer

**Comment by vhvb1989** [comment]
I will use this issue to covert this issue I found while testing about bad behavior if adding one header that starts with space to a request like
"  header":"value"
This makes libcurl to consider no header and produces unexpected behavior on the http request internals (other headers or body got corrupted with header value)

**Comment by JeffreyRichter** [comment]
Can you make it a precondition test to see if the header starts with whitespace?
It really should never happen.

**Comment by JeffreyRichter** [comment]
We are providing a CONTRACT to the consumer of our HTTP request & response abstractions. The contract has to be clear and the consumer of our abstractions does not know (or care) whether CURL is ultimately what is being used to send/receive HTTP requests. 

So, when customer pass us request headers, what do we expect of them and what will we do for them? Will we accept headers/values with whitespace? I say NO and therefore we can precondition test these to verify that they have adhered to our contract. But, we do not need code to trim whitespace. 

For response headers, when we give keys/values back to the customer, our contract should be that they do NOT have whitespace in them (regardless of what the service sent to us). So, we should trim whitespace. This cannot be done as a precondition check as the data comes from the service (not the customer) and because whitespace is allowed per the RFC. 

Now, we can look at whatever CURL needs. Whatever it does MUST NOT impact the customer of our HTTP request/response abstractions. That is, the customer MUST be able to replace the transport with something other than CURL and the code using out HTTP abstractions MUST NOT require any changes - it MUST work. So, the CURL transport has to do what ever CURL needs transparently without breaking the contract we have with the customer.

**Comment by vhvb1989** [comment]
> For response headers, when we give keys/values back to the customer, our contract should be that they do NOT have whitespace in them (regardless of what the service sent to us). So, we should trim whitespace.

Trim is an expensive operation on http_response.  We have all the response in one single buffer.
So we have two options
-  Most expensive: update content shifting everything to the left as many places as white spaces.
-  Less expensive but hacky:  build az_pair for the returned header without the white spaces.  So, we still have the white spaces on the response, we just help customers to get rid of it with pointing to the next memory address.

Would you go with the hacky option @JeffreyRichter ?

**Comment by vhvb1989** [comment]
thinking as a customer, I would ask myself "why this guys are helping me to trim headers from response and blocking me from adding a header with spaces in the request. Why don't they just do the same with request and move the pointers for me"  (but that's probably me as an user that could know too much about what's happening XD)

**Comment by JeffreyRichter** [comment]
I'd go with the less expensive option of producing spans that trim out the whitespace.
Our API gets to define the contract. The SDK wants to do as little work as possible to keep code small & fast. For request headers, there is no reason why a customer should be passing keys/values with whitespace into our APIs. We don't want to execute code that validates this (except as a precondition test); we just want the customer to do the right thing. And, the customer has to go out of their way to do the wrong this, so adhering to the contract should be trivially easy. 

For response headers, the customer is not calling into us and it is legal for service to add whitespace in front/after a header key/value but the whitespace is NOT part of the header's key or value itself. Our APIs return a span over the header key and the header value and whitespace is NOT part of these and so we should adjust the spans we give to customer to exclude the whitespace. Also, over time, the server might change what whitespace it injects into the full HTTP response. This change should NOT impact customer code. Also, 1 Azure service might inject whitespace and another Azure service might not; by having our SDK remove whitespace from the returned spans, the customer is abstracted away from these service/versioning differences.

The basic question is this: Is whitespace part of an HTTP header key or value? The answer is NO. So if the customer passes a value with whitespace, that is an invalid key/value. If the service injects whitespace in a response, the whitespace is a delimiter and is NOT an invalid header key/value.

Hence, we have differing behavior because the meaning of whitespace is different between request headers and response headers.

**Comment by ahsonkhan** [comment]
I don't think this issue has been completely addressed since character validation is still left.

**Comment by vhvb1989** [comment]
> I don't think this issue has been completely addressed since character validation is still left.

see: https://github.com/Azure/azure-sdk-for-c/pull/684
