### ISSUE TITLE
Documentation: az_log_set_callback should be called first, before az_log_set_classifications

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-sdk-for-c#675]
From https://github.com/Azure/azure-sdk-for-c/pull/670#discussion_r419028461 for details @JeffreyRichter pointed out:

> if another thread calls into the SDK, there is a race condition where the callback could get called before the classifications are set.

My proposal is to unify 

```
az_log_set_callback(_log_listener);
az_log_set_classifications(classifications);
```

Into a single function that has the race condition solved:

`az_log_set_callback(log_listener, classifications);`

**Comment by JeffreyRichter** [comment]
Yes, we thought about this. It's a matter of perspective.
We wanted to enable the scenario where the classifications being logged can change while the app is in flight and so we are able to atomically replace the classifications.
But, we don't expect the callback to be changed while the app is in flight.

Based on what I said above, your old order is fine: set the callback 1st and then the classification. But, since it is your intent in the test to NOT change classifications after initialization, it is more logical to set the classifications first and then the callback.

You could also easily say that you're single threaded and you do not dynamically change classifications so no race condition is possible and either order is just fine. I just wanted to make you aware of things to think about and order would have more impact on a sample (where customers may copy the code into their own and add threading or add dynamic classification swapping) than on a test.

**Comment by CIPop** [comment]
@JeffreyRichter the way I read your initial comment I understood there is a race condition if an app chooses to do this from multiple threads. 
Thanks for explaining: I completely agree with the scenario of apps setting the listener then enabling/disabling classification - I think that is very useful if we need to activate logging temporarily on a deployed device.

Changing the title to clarify this is a documentation-only issue and that apps should always configure the callback first then switch classifications on/off as required.

**Comment by ahsonkhan** [comment]
There is an argument to be made that it isn't necessary for the caller to always call these methods in one order or another.
