### ISSUE TITLE
Turn relative paths within docs to absolute links within README markdowns so they are doxygen friendly

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#746]
See https://github.com/Azure/azure-sdk-for-c/pull/735#issuecomment-627101719

GitHub renders markdown correctly, when it comes to relative paths, but that doesn't work well for standalone doxygen generated docs.

For example, using `[/sdk](sdk)` within the root README works and forwards to https://github.com/Azure/azure-sdk-for-c/tree/master/sdk, but the link doesn't get resolved in doxygen.

>   For information about using a specific client library, see the README file located in the client library's folder which is a subdirectory under the [`/sdk`](sdk) folder.

Other relative links will result in 404:
https://djurekdocs.z5.web.core.windows.net/mono/sdk/core/core/README.md#Porting-the-Azure-SDK-to-Another-Platform
![image](https://user-images.githubusercontent.com/6527137/81756095-9a589a00-946f-11ea-8704-1e4fb5b27e03.png)

cc @gilbertw, @vhvb1989, @antkmsft, @danewalton, @danieljurek

**Comment by danewalton** [comment]
I don't think this is needed. [This here in the doxygen docs](https://www.doxygen.nl/manual/markdown.html#md_links) shows relative links should work. I think the example you gave could be fixed by linking specifically to the readme and not the directory:
```
[/sdk](/sdk/readme.md)
```

**Comment by ahsonkhan** [comment]
cc @KarishmaGhiya since you are working on the general problem with links in READMEs and docs (for C/C++, we use doxygen).

One concern with making links point to master (brought up here: https://github.com/Azure/azure-sdk-for-c/pull/853#issue-439522671) is that those links won't resolve in the contributors working branch.

**Comment by weshaggard** [comment]
Our general guidance around links is posted at https://github.com/Azure/azure-sdk/blob/master/docs/policies/README-TEMPLATE.md and is to use links to master instead of relative links. The primary reason is that the contents of these MD files end up getting used in a lot more context then on github. For example they are consumed by docs, samples, package managers, etc. We used to have the guidance of using relative links but we found more and more folks taking the md files from our repo's and having issues with broken links so we decided to change the guidance to use links to master.

I understand the scenario of links not working in branches when we do that but I think that is a relatively small price to pay in our overall system of where these links are consumed. I will also say that in general the only long lived branch is master and feature branches are typically scoped to a particular time so most folks are browsing source in master. 

I will also add that if we are sure the only consumers of a MD file are folks working on github then we can consider using relative links in those cases but for the most part we have found that a lot more places consume these MD files then only on github.

**Comment by danieljurek** [comment]
In order for this to merge properly we need to ensure that there is a tool in place to convert `blob/<branch>/` to `blob/<tag>/` in the URL on publishing.

**Comment by weshaggard** [comment]
Yes that works is part of @KarishmaGhiya's link validation epic https://github.com/Azure/azure-sdk/issues/818

**Comment by RickWinter** [comment]
@danieljurek please break this issue up into the two issues

**Comment by danieljurek** [comment]
Split off https://github.com/Azure/azure-sdk-for-c/issues/1044 to track the link validation work. This bug should track the remaining work to turn relative links in the docs to absolute links. I've linked it to the epic https://github.com/Azure/azure-sdk/issues/818
