### ISSUE TITLE
Improve build flag testing

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#760]
Need validation that CMake is setting the proper build options.  Also need to validate that correct parts of the code are built when those options are ON/OFF

**Comment by antkmsft** [comment]
I propose us to have:
1. `VERIFY_CMAKE` compile flag. We don't document it, and we wet it to on for our CI/CD builds (by supplying `-DVERIFY_CMAKE=ON`among with the other parameters)
2. We currently have `TRANSPORT_CURL` option. In az_curl's CMakeFile we should set `TRANSPORT_CURL_BUILT_VERIFIED` to ON. Otherwise, if the az_curl was not included and built, it is supposed to be OFF.
3. Back to root directory's Cmakefile, which contains `VERIFY_CMAKE`. At the very bottom, we have logic like this:
```
if (VERIFY_CMAKE == ON)
{
    if (TRANSPORT_CURL == ON)
    {
        if (NOT TRANSPORT_CURL_BUILT_VERIFIED == ON)
        {
            Make CMake to fail somehow.
        }
        // else we're good.
    }
    else // TRANSPORT_CURL == OFF
    {
        if (NOT TRANSPORT_CURL_BUILT_VERIFIED == OFF)
        {
            // We were not supposed to build Curl, yet it looks like it got built
            Make CMake to fail somehow.
        }
        // else we're good.
    }
}
```

**Comment by vhvb1989** [comment]
I think this was already done by @antkmsft  ??  as part of the CI legs enhancement?
