### ISSUE TITLE
[BUG] .clang_format pointer alignment

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#93]
**Describe the bug**
.clang_format `PointerAlignment` should be left or right aligned. In my humble opinion, middle is the worst of the three.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by sergey-shandar** [comment]
I thought, the right alignment is the worst one :-D

**Comment by danewalton** [comment]
I mean I'm all for the left to be honest unless others are opposed. That's how all of our code for the C SDK has it :)

**Comment by antkmsft** [comment]
@danewalton, I disagree that it is the worst of both worlds.
This is really _subjective_, and arguments go both ways. Sticking it to name is more common in C world, sticking it to the left side is more popular in C++ world, and I personally like it more as well. I view middle as a compromise, and as long as it is not right alignment, I am fine. We had right alignment initially, and middle is a step forward from that :)
1. `int const * const` is easier to read than `int const *const x`, you clearly see both sides, and can get which CV-modifier applies where.
2. One could argue that you read `int *p` as "`int` is what you get when you write `*p`". However, this is not the case with `*const p`, and with C++ references: write `int &ref = n`, you write `&ref` and you won't get `int`. I know this is C SDK, but we might want to reuse the same style for consistency. In C++ world `int* x` is more common than in C, although `int *x` is also used. So, having it in between is a compromise, in my view.
3. Sticking `*` to name really matters in single-line multiple variable declarations (which we don't do), but even then there is no consistency:
`typedef int * int_ptr;
int x = 3;
int_ptr a = &x, b = &x; // now asterisk is the part of the type`
So, sometimes (only in single-line multiple variable declarations without typedefs?) it rather sticks to variable; and sometimes it sticks to type (typedefs); and in most cases you can't tell the difference - so again, I view middle as compromise.

As of this style being used anywhere else: it is used in boost (example: https://github.com/boostorg/smart_ptr/blob/274ec17836bfbfd85159ef3c358031b31fc3c6ea/include/boost/smart_ptr/shared_ptr.hpp#L217), however they are not very consistent. I've seen at least int* p and int * p in the same file there, and I won't be surprised if there are also some int *p's in their code.

**Comment by antkmsft** [comment]
BTW, speaking of code style: can we start putting "{" on the new line? It is great to for books, where less new lines and more compact code is a benefit. But as of the code fitting on one screen, we all use displays with large enough resolution to fit plenty of code to read, and I don't think that less logical and visual spacing => better readability. It is nice to see an one-line vertical space between the last parameter of a function, and first line of the function implementation; easier to read. IMHO.

**Comment by danewalton** [comment]
Completely agree with the { on the new line. I’m 99% sure the rest of the IoT SDK team would agree as that’s what we currently do.
As for the pointer alignment, it’s not a hill I’m willing to die on but I will be cringing for a while when autoformat does it’s thing.

**Comment by rafilho** [comment]
@antkmsft, I believe the middle pointer is a terrible compromise, IMO. :) Looking at the boost code:

`template<class T, class U> shared_ptr<T> reinterpret_pointer_cast( shared_ptr<U> const & r ) BOOST_SP_NOEXCEPT
{
    (void) reinterpret_cast< T* >( static_cast< U* >( 0 ) );

    typedef typename shared_ptr<T>::element_type E;

    E * p = reinterpret_cast< E* >( r.get() );
    return shared_ptr<T>( r, p );
}`

Few counter arguments:

- As you said, they are not consistent: T* and U* on the casts do not follow the rule. 
- Spaces on each side of the * or & make them look like operators. For example, at my first sight of the line below, I though we were multiplying E * p:

`E * p = reinterpret_cast< E* >( r.get() );`

Same happens when I look at the '&' between spaces. It looks like we are doing a bitwise operator.

I do not have preferences between left or right. I understand personal preferences of people liking either one. But compromising for a third option that almost no one in the world uses it (except Boost), just creates a third problem IMO. 

From our side, we will not follow the middle pointer if this is the proposal of the guideline. **So, consider that as my exception request.** :) 

BTW, we had closed on that exact question during one of our meetings with consensus, even if it was a compromise for something. So, to be honest, I do not know how this got into the clang file, since it is against what we decided as a guideline decision.

**Comment by antkmsft** [comment]
I am glad we can discuss this.

IMO:
Left alignment - stick to type:
* Pros: `int const* const x`: `int const*` relates to type, `const x` - to variable.
* Cons: multiple variable declarations which we don't use.
Users: larger part of the C++ world, starting with Bjarne Stroustroup's book. Although right alignment is not uncommon.

Middle:
* Pros: visual spacing, if you read `*` as `ptr`, or as a separator between `int const` and `const`.
* Cons: to an untrained eye, looks like an operator
Users: Boost (mostly)

Right:
* Pros: multiple variable declarations
* Cons: logically tied to variable name and not the type, looks ridiculous for C++ references (especially if you justify with the logic that for pointers, when you have an expression `int *x`, `int` is what you get, when you write `*x`).
Users: C world.

**Comment by sergey-shandar** [comment]
Note: in Azure SDK code we almost always use `const` before variable name. So most of our code looks like this

```c
int * const p = ...;
```

Instead of like this
```c
int * p = ...;
```

**Comment by antkmsft** [comment]
Agree, but define "looks good" :)

**Comment by rafilho** [comment]
What I am hearing is that most people don't like right alignment compared to left alignment? Which means, we should go for left alignment?

I.e.:
int* const p = …;
int* p = …;

According to @antkmsft's table above, it has a large base of users (maybe the largest), and its main con is already mitigated by our guideline anyway (since we do not use multiple declarations on the same line).

Do we have an agreement? :)

**Comment by antkmsft** [comment]
I personally feel very good about left alignment, like the middle alignment, and don't like right alignment. I understand that there is no killer argument for either one, or, at least, I think I won't be able to bring any more arguments to the discussion, other than I brought above, so if you are not convinced with what you read above, I probably won't be able to shift your opinion. Realistically, it is not likely we will run into a real issue with either one.
But I also understand the importance of liking the pointer style in the code that you write. Given all that, I am personally fine to go with the popular vote for pointer alignment, even though I'd cringe a bit if I'd have to use right alignment.

**Comment by rafilho** [comment]
@sergey-shandar , @danewalton: are we good with closing on left alignment?

**Comment by antkmsft** [comment]
In defense of middle alignment, it is recommended in "Embedded C Coding Standard" by Michael Barr: https://barrgroup.com/Embedded-Systems/Books/Embedded-C-Coding-Standard/White-Space-Rules/Spaces (3.1.e)  (see? it is not that exotic :))

**Comment by danewalton** [comment]
@antkmsft @rafilho @sergey-shandar 
https://github.com/Azure/azure-sdk-for-c/pull/111

**Comment by sergey-shandar** [comment]
@rafilho I'm ok with this. I like more `middle` but I can live with left.
