### ISSUE TITLE
sscanf issue in az_span.c

### ISSUE THREAD

**Issue by bo-ms** [Azure/azure-sdk-for-c#962]
sscanf is supported in some IDEs (IAR, VS), but it is not supported well in some other IDEs, such as: STM32Cube (1.3.0), MCUXpresso(11.1.1)  and MPLAB (5.35).

For example, the value of chars_consumed is 0 after running following code in STM32Cube IDE.
```
    int32_t result;
    int32_t chars_consumed = 0;
    int32_t n = sscanf((char*)"200", "%03llu %n", &result, &chars_consumed);
```
In VS:
![image](https://user-images.githubusercontent.com/50469338/88631125-3d6e9680-d0e4-11ea-8e57-1ded0be8348f.png)

In IAR:
![image](https://user-images.githubusercontent.com/50469338/88631949-8b37ce80-d0e5-11ea-87b6-b97d7b4fc6f6.png)

In STM32Cube:
![image](https://user-images.githubusercontent.com/50469338/88632203-d651e180-d0e5-11ea-8701-9a2a77fa2556.png)

[az_span.c](https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/src/azure/core/az_span.c) also uses sscanf() to process data, it will lead to failure in some IDEs , what do you think?

```
static void _az_span_ato_number_helper(
    az_span source,
    bool is_negative_allowed,
    char* format,
    void* result,
    bool* success)
{
...

  int32_t chars_consumed = 0;
  int32_t n = sscanf((char*)source_ptr, format, result, &chars_consumed);

  if (success != NULL)
  {
    // True if the entire source was consumed by sscanf, it set the result argument, and it didn't
    // set errno to some non-zero value.
    *success = size == chars_consumed && n == 1 && errno == 0;
  }

...
}
```

**Comment by CIPop** [comment]
@bo-ms from my limited experience scanf usually runs into either stack issues or has features disabled. 
1. Have you checked that scanf has sufficient stack?
2. In STCube I know there is this setting for "Use float with printf/scanf from newlib":

![image](https://user-images.githubusercontent.com/8635911/88699602-67ac5e00-d0bc-11ea-8476-981f103628b2.png)

This doesn't seem to be your issue but there might be other options that need to be set to enable the feature?


@gilbertw @ahsonkhan I think we should avoid as much as possible using `sscanf`/`sprintf`. If we cannot achieve this, we'll need to add some prerequisites on what needs to be enabled in the supported compilers to make our SDK work (which will likely increase the binary output size considerably). Can we instead consider alternatives from the C99 stdlib (atoi/atol)?

**Comment by ahsonkhan** [comment]
> Can we instead consider alternatives from the C99 stdlib (atoi/atol)?

There were several discussions of what approaches to use, and we landed on `sscanf` based on @JeffreyRichter's recommendation. The concern with atoi/atol (and strtod) is that they require 0-terminated strings and hence end up with data copies (and requiring destination buffers). It is possible for us to hand write our integer parsing APIs (since they are relatively simple), but double/floating point parsing is quite difficult to get right, which is why we decided to leverage some built-in implementation.

**Comment by bo-ms** [comment]
@CIPop Yes, I verified sscanf() has enough stack, and I got the same issue with following setting.
![image](https://user-images.githubusercontent.com/50469338/88741842-40fd2e80-d173-11ea-9f29-2c4f1bbb6114.png)

**Comment by bo-ms** [comment]
@ahsonkhan Yes, it is actually a blocking issues for checking return status value (such as: 200) in [device twin](https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/src/azure/iot/az_iot_hub_client_twin.c)
```
AZ_NODISCARD az_result az_iot_hub_client_twin_parse_received_topic(
    az_iot_hub_client const* client,
    az_span received_topic,
    az_iot_hub_client_twin_response* out_twin_response)
{
...

      // Get status and convert to enum
      uint32_t status_int;
      AZ_RETURN_IF_FAILED(az_span_atou32(status_str, &status_int));
      out_twin_response->status = (az_iot_status)status_int;

    ...
}
```

**Comment by ahsonkhan** [comment]
@bo-ms, from the locals in your screenshot, it looks like in `STM32Cube` the `result` is correctly being set to `200` but the  `chars_consumed` isn't being set. That is certainly a strange behavior.

> STM32Cube (1.3.0), MCUXpresso(11.1.1) and MPLAB (5.35).

Do you know what C compiler versions (of GCC/Clang/etc.) do these IDEs build the code against? I want to try to get a local repro to investigate why this is happening, but don't have those IDEs installed atm.

**Comment by bo-ms** [comment]
@ahsonkhan you are correct, the result is set correctly, but the chars_consumed is not being set. Same behaviors with "%03llu%n" or "200\0"

C compiler version in STM32Cube: arm-none-eabi-gcc.exe (GNU Tools for STM32 7-2018-q2-update.20190328-1800) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

STM32Cube IDE link: https://www.st.com/en/development-tools/stm32cubeide.html

**Comment by ahsonkhan** [comment]
cc @joshfree

**Comment by hihigupt** [comment]
how about if we use "%00lu%n" instead of "%00llu%n"...

I tried to validate the "%00lu%n" this and it works for stm32.

possibly because in embedded most of people uses nano-lib implementation of stdlib and for size reason it uses nano format for printf/scanf family (i.e c89 and only support 32 bit).

Check this out:
For more details about "nano" formatting option, please see newlib readme file,
        search for '--enable-newlib-nano-formatted-io':
        https://sourceware.org/newlib/README

**Comment by ahsonkhan** [comment]
**Here are some options:**
A) Don't use sscanf for any integer parsing (for both 32 and 64-bit), write our own implementation, and only use it for double parsing. This seems like a reasonable fix but we should keep code size in mind.
B) As @hihigupt mentioned, use only 32-bit format strings for 32-bit integer parsing, and make folks opt-in to the 64-bit support. This has concerns with overflow detection, which is why the 64-bit format string was used, even in 32-bit. So the overflow detection need to be implemented differently if we go with this option.

**That said, let's make sure:**
1) The implementation of double parsing using `sscanf`, as is, works on all the commonly used/supported IDEs.
2) If we go with option (B), that folks who do want to use 64-bit integers, are able to, possibly with the workaround to enable the nano formatting option.
