### ISSUE TITLE
Hardcoded links to preview.2

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-c#998]
The IoT readme hardcodes preview.2 docs.

```
[azure_sdk_for_c_doxygen_hub_docs]: https://azuresdkdocs.blob.core.windows.net/$web/c/docs/1.0.0-preview.2/az__iot__hub__client_8h.html
[azure_sdk_for_c_doxygen_provisioning_docs]: https://azuresdkdocs.blob.core.windows.net/$web/c/docs/1.0.0-preview.2/az__iot__provisioning__client_8h.html
```

**Comment by ahsonkhan** [comment]
Do we need to fix the following as well, in https://github.com/Azure/azure-sdk-for-c/blob/a2b09b5d884c21336702d35bd349f0998edb6208/sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md

> Username: myiothub.azure-devices.net/mydeviceid/?api-version=2018-06-30&DeviceClientType=c%2F**1.0.0-preview.2**

**Comment by RickWinter** [comment]
@danewalton Is there anything blocking this getting fixed before GA?

**Comment by danewalton** [comment]
We could but I don't think it's a huge deal. On levels of priority, fixing that one log message is pretty low.

**Comment by ahsonkhan** [comment]
I think doc navigation of some of the generated IoT docs might break in the future if we don't update the links.

**Comment by danewalton** [comment]
Oh sorry I was meaning the node mcu thing you pointed out Ahson: didn't quite understand the root issue. Yea I'll check it out.

**Comment by danewalton** [comment]
Is there not a way for us to link to specific functionality's docs?

**Comment by RickWinter** [comment]
> Is there not a way for us to link to specific functionality's docs?

@danieljurek What is the proper way to link to version specific reference docs within the docs?

**Comment by danieljurek** [comment]
Linking to functional docs can probably be accomplished using the Doxygen [`\link` command](https://www.doxygen.nl/manual/commands.html#cmdlink). This would be one instance in which Doxygen and markdown conceptual docs play well together. 

However that won't render nicely in GitHub markdown. And we'll have this same problem if we try rendering conceptual docs in docfx. 

There is chicken/egg problem here... The easiest way I can think to solve it today is to "predict" what the link is going to be and make sure that that link is present in the `master` branch at the SHA that is published. We'd need to make sure that the link checker doesn't validate these links because they won't be valid until after the docs are published. 

@scbedd might know of some potential solutions here beyond my brief consideration.

**Comment by danewalton** [comment]
Is it too much of an issue to make an `aka.ms` link for each? They have an API where we can update them programmatically if we wanted. Otherwise we update them manually for now and then once for each GA release after that.
